name: 'Label stale issues and pull requests'
on:
  workflow_dispatch:
  schedule:
    # Runs every day 1:30 UTC
    - cron: '30 1 * * *'



jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v4
        with:
          stale-issue-message: "This issue has been labeled stale because it has been open 60 days with no activity."
          stale-pr-message: "This pull request has been labeled stale because it has been open 3 days with no activity."
          days-before-issue-stale: 60
          days-before-pr-stale: 3
          days-before-close: -1
          days-before-pr-close: -1
